name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
      - "Dockerfile"
      - "Dockerfile-extra"
      - "Dockerfile-bare"
      - "config/**"
  schedule:
    - cron: "0 4 * * 3"
  workflow_dispatch:

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      -
        name: Build images
        run: |
          docker buildx build --push \
          --tag ${{ secrets.DOCKER_USERNAME }}/pwnpad:latest \
          --platform linux/amd64,linux/arm64 .
  build-extra:
    needs: build-base
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      -
        name: Build images
        run: |
          docker buildx build --push -f Dockerfile-extra \
          --tag ${{ secrets.DOCKER_USERNAME }}/pwnpad:extra \
          --platform linux/amd64,linux/arm64 .
  build-bare:
    needs: build-extra
    runs-on: ubuntu-latest
    steps:
      -
        name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 45000
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      -
        name: Build images
        run: |
          docker buildx build --push -f Dockerfile-bare \
          --tag ${{ secrets.DOCKER_USERNAME }}/pwnpad:bare \
          --platform linux/amd64,linux/arm64 .
