name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
      - 'p2'
  schedule:
    - cron: "0 8 * * 3"

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      -
        name: Build images
        run: |
          docker buildx build --push \
          --tag ${{ secrets.DOCKER_USERNAME }}/pwnbox2:latest \
          --platform linux/amd64,linux/arm64 .
  build-extra:
    needs: build-base
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      -
        name: Build images
        run: |
          docker buildx build --push -f Dockerfile-extra \
          --tag ${{ secrets.DOCKER_USERNAME }}/pwnbox2:extra \
          --platform linux/amd64,linux/arm64 .
